import { GameConfig } from "../../gameConfig";
import { util } from "../../utils/util";
import type { MapDef } from "../mapDefs";
import { MapId } from "../types/misc";
import { Main, type PartialMapDef } from "./baseDefs";

const mapDef: PartialMapDef = {
    mapId: MapId.FixedLoot,
    desc: { name: "Fixed Loot", icon: "", buttonCss: "" },
    gameConfig: {
        planes: {
            // timings: [
            //     {
            //         circleIdx: 2,
            //         wait: 0,
            //         options: { type: GameConfig.Plane.Airdrop },
            //     },
            //     {
            //         circleIdx: 3,
            //         wait: 0,
            //         options: { type: GameConfig.Plane.Airdrop },
            //     },
            // ],
        },
    },
    lootTable: {
        tier_club_bonus: [
            { name: "model94", count: 1, weight: 1 },
            { name: "an94", count: 1, weight: 1 },
        ],
        tier_world: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.7 },
            { name: "tier_packs", count: 1, weight: 0.5 },
            { name: "tier_medical", count: 1, weight: 1.5 },
            { name: "tier_ammo", count: 1, weight: 2.5 },
            { name: "tier_guns", count: 1, weight: 2 },
        ],
        tier_surviv: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.2 },
            { name: "tier_medical", count: 1, weight: 4 },
            { name: "tier_packs", count: 1, weight: 1 },
        ],
        tier_bugler_crate: [
            { name: "model94", count: 1, weight: 1 },
            { name: "an94", count: 1, weight: 1 },
        ],
        tier_container: [
            { name: "tier_scopes", count: 1, weight: 0.2 },
            { name: "tier_armor", count: 1, weight: 1 },
            { name: "tier_packs", count: 1, weight: 0.3 },
            { name: "tier_medical", count: 1, weight: 0.8 },
            { name: "tier_ammo", count: 1, weight: 0.5 },
            { name: "tier_guns", count: 1, weight: 0.6 },
        ],
        tier_leaf_pile: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.5 },
            { name: "tier_packs", count: 1, weight: 1 },
            { name: "tier_medical", count: 1, weight: 1 },
            { name: "tier_ammo", count: 1, weight: 1 },
        ],
        tier_soviet: [
            { name: "tier_scopes", count: 1, weight: 1 },
            { name: "tier_armor", count: 1, weight: 1.5 },
            { name: "tier_packs", count: 1, weight: 1 },
            { name: "tier_medical", count: 1, weight: 2 },
            { name: "tier_ammo", count: 1, weight: 3 },
            { name: "tier_guns", count: 1, weight: 6 },
        ],
        tier_toilet: [
            { name: "tier_scopes", count: 1, weight: 0.5 },
            { name: "tier_guns", count: 1, weight: 0.2 },
            { name: "tier_medical", count: 1, weight: 1.0 },
        ],
        tier_scopes: [
            { name: "2xscope", count: 1, weight: 0.6 },
            { name: "4xscope", count: 1, weight: 1 },
            { name: "8xscope", count: 1, weight: 0 },
            { name: "15xscope", count: 1, weight: 0 },
        ],
        tier_armor: [
            { name: "helmet01", count: 1, weight: 8.5 },
            { name: "helmet02", count: 1, weight: 7 },
            { name: "helmet03", count: 1, weight: 3 },
            { name: "chest01", count: 1, weight: 8.5 },
            { name: "chest02", count: 1, weight: 7 },
            { name: "chest03", count: 1, weight: 3 },
        ],
        tier_packs: [
            { name: "backpack01", count: 1, weight: 7 },
            { name: "backpack02", count: 1, weight: 4 },
            { name: "backpack03", count: 1, weight: 1 },
        ],
        tier_medical: [
            { name: "bandage", count: 5, weight: 6 },
            { name: "healthkit", count: 1, weight: 4 },
            { name: "soda", count: 1, weight: 13 },
            { name: "painkiller", count: 1, weight: 6 },
        ],
        tier_throwables: [
            { name: "frag", count: 1, weight: 1 },
            { name: "smoke", count: 1, weight: 1 },
            { name: "snowball", count: 1, weight: 0 },
            { name: "mirv", count: 1, weight: 0.05 },
        ],
        tier_ammo: [
            { name: "9mm", count: 60, weight: 8 },
            { name: "762mm", count: 60, weight: 8 },
            { name: "556mm", count: 60, weight: 8 },
            { name: "12gauge", count: 10, weight: 10 },
        ],
        tier_ammo_crate: [
            { name: "9mm", count: 60, weight: 5 },
            { name: "762mm", count: 60, weight: 5 },
            { name: "556mm", count: 60, weight: 5 },
            { name: "12gauge", count: 10, weight: 7 },
            { name: "50AE", count: 21, weight: 1 },
            { name: "308sub", count: 5, weight: 1 },
            { name: "flare", count: 1, weight: 1 },
        ],
        tier_vending_soda: [
            { name: "soda", count: 1, weight: 6 },
            // { name: "tier_ammo", count: 1, weight: 1 },
        ],
        tier_sv98: [
            { name: "sv98", count: 1, weight: 10 },
            { name: "", count: 1, weight: 0 },
        ],
        tier_mosin: [
            { name: "mosin", count: 1, weight: 10 },
            { name: "", count: 1, weight: 0 },
        ],
        tier_scout: [
            { name: "scout_elite", count: 1, weight: 10 },
            { name: "", count: 1, weight: 0 },
        ],
        tier_scopes_sniper: [
            { name: "4xscope", count: 1, weight: 0.2 },
            { name: "8xscope", count: 1, weight: 0 },
            { name: "15xscope", count: 1, weight: 0 },
        ],
        tier_mansion_floor: [{ name: "outfitCasanova", count: 1, weight: 1 }],
        tier_vault_floor: [{ name: "outfitJester", count: 1, weight: 1 }],
        tier_police_floor: [{ name: "outfitPrisoner", count: 1, weight: 1 }],
        tier_chrys_01: [{ name: "outfitImperial", count: 1, weight: 1 }],
        tier_chrys_02: [{ name: "katana", count: 1, weight: 1 }],
        tier_chrys_03: [
            //{ name: "2xscope", count: 1, weight: 1 },
            //{ name: "4xscope", count: 1, weight: 0.3 },
            //{ name: "8xscope", count: 1, weight: 0 },
            { name: "helmet04_medic", count: 1, weight: 1 },
        ],
        tier_chrys_case: [{ name: "", count: 1, weight: 1 }],
        tier_chrys_chest: [
            { name: "", count: 1, weight: 1 },
            { name: "katana", count: 1, weight: 1 },
            { name: "katana_rusted", count: 1, weight: 1 },
            { name: "katana_orchid", count: 1, weight: 1 },
        ],
        tier_eye_02: [{ name: "stonehammer", count: 1, weight: 1 }],
        tier_eye_block: [
            { name: "spas12", count: 1, weight: 1 },
            // { name: "ots38_dual", count: 1, weight: 1 },
            // { name: "flare_gun", count: 1, weight: 1 },
            // { name: "colt45", count: 1, weight: 1 },
            // { name: "45acp", count: 1, weight: 1 },
            // { name: "painkiller", count: 1, weight: 1 },
            // { name: "m4a1", count: 1, weight: 0.4 },
            //  { name: "m249", count: 1, weight: 0.05 },
            // { name: "awc", count: 1, weight: 0.05 },
            //{ name: "pkp", count: 1, weight: 0.05 },
        ],
        tier_sledgehammer: [{ name: "sledgehammer", count: 1, weight: 1 }],
        tier_chest_04: [
            { name: "p30l", count: 1, weight: 20 },
            { name: "p30l_dual", count: 1, weight: 1 },
        ],
        tier_woodaxe: [{ name: "woodaxe", count: 1, weight: 1 }],
        tier_club_melee: [{ name: "machete_taiga", count: 1, weight: 1 }],
        tier_guns: [
            { name: "famas", count: 1, weight: 2 },
            { name: "hk416", count: 1, weight: 8 },
            { name: "mk12", count: 1, weight: 0.9 },
            { name: "pkp", count: 1, weight: 0.0015 },
            { name: "m249", count: 1, weight: 0.006 },
            { name: "ak47", count: 1, weight: 8 },
            { name: "scar", count: 1, weight: 2 },
            { name: "dp28", count: 1, weight: 1.5 },
            // { name: "mosin", count: 1, weight: 0.2 *0.3 },
            { name: "m39", count: 1, weight: 0.8 },
            { name: "vss", count: 1, weight: 0.1 },
            { name: "mp5", count: 1, weight: 6 },
            { name: "mac10", count: 1, weight: 6 },
            { name: "ump9", count: 1, weight: 3 },
            { name: "m870", count: 1, weight: 12 },
            { name: "m1100", count: 1, weight: 0 },
            { name: "mp220", count: 1, weight: 4 },
            { name: "saiga", count: 1, weight: 0.1 },
            { name: "ot38", count: 1, weight: 3 },
            { name: "m9", count: 1, weight: 5 },
            { name: "m93r", count: 1, weight: 4 },
            { name: "glock", count: 1, weight: 4 },
            { name: "deagle", count: 1, weight: 0.5 },
            { name: "vector", count: 1, weight: 1 },
            // { name: "sv98", count: 1, weight: 0.03 * 0.9 },
            { name: "spas12", count: 1, weight: 3 },
            { name: "qbb97", count: 1, weight: 0.5 },
            { name: "flare_gun", count: 1, weight: 0.6 },
            { name: "flare_gun_dual", count: 1, weight: 0.00017 },
            { name: "groza", count: 1, weight: 2 },
            // { name: "scout_elite", count: 1, weight: 0.1 *0.3 },
            // { name: "blr", count: 1, weight: 0.5 *0.4 },
            { name: "scorpion", count: 1, weight: 0.5 },
            { name: "m4a1", count: 1, weight: 0.5 },
        ],
        tier_police: [
            { name: "scar", count: 1, weight: 1 },
            { name: "helmet03", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 1 },
            { name: "backpack03", count: 1, weight: 1 },
        ],
        tier_ring_case: [
            { name: "grozas", count: 1, weight: 5 },
            { name: "ots38_dual", count: 1, weight: 0.1 },
            { name: "m9", count: 1, weight: 0 },
            { name: "pkp", count: 1, weight: 0.15 },
            // { name: "blr", count: 1, weight: 0.3 * 0.5 },
        ],
        tier_chest: [
            { name: "hk416", count: 1, weight: 2 },
            { name: "ak47", count: 1, weight: 13 },
            { name: "groza", count: 1, weight: 3 },
            { name: "famas", count: 1, weight: 1 },
            { name: "mk12", count: 1, weight: 4 },
            { name: "mp220", count: 1, weight: 10 },
            { name: "spas12", count: 1, weight: 9 },
            { name: "dp28", count: 1, weight: 1 },
            // { name: "mosin", count: 1, weight: 2 *0.4 },
            { name: "m39", count: 1, weight: 0.1 },
            { name: "scar", count: 1, weight: 2 },
            { name: "saiga", count: 1, weight: 2 },
            { name: "deagle", count: 1, weight: 0.7 },
            // { name: "sv98", count: 1, weight: 0.2 * 0.4},
            { name: "vector", count: 1, weight: 1 },
            { name: "m249", count: 1, weight: 1 },
            { name: "pkp", count: 1, weight: 0.3 },
            { name: "helmet01", count: 1, weight: 0 },
            { name: "helmet02", count: 1, weight: 0 },
            { name: "helmet03", count: 1, weight: 0 },
            { name: "4xscope", count: 1, weight: 0 },
            { name: "8xscope", count: 1, weight: 0 },
            { name: "blr", count: 1, weight: 1.5 },
            { name: "scorpion", count: 1, weight: 0.5 },
            { name: "m4a1", count: 1, weight: 0.5 },
        ],
        tier_conch: [
            { name: "outfitAqua", count: 1, weight: 1 },
            { name: "outfitCoral", count: 1, weight: 1 },
        ],
        tier_noir_outfit: [{ name: "outfitNoir", count: 1, weight: 1 }],
        tier_khaki_outfit: [{ name: "outfitKhaki", count: 1, weight: 1 }],
        tier_pirate_melee: [{ name: "hook", count: 1, weight: 1 }],
        tier_hatchet: [
            { name: "blr", count: 1, weight: 1 },
            // { name: "vector", count: 1, weight: 5 },
            // { name: "hk416", count: 1, weight: 2 },
            // { name: "mp220", count: 1, weight: 1 },
            // { name: "m249", count: 1, weight: 0.1 },
            // { name: "pkp", count: 1, weight: 0.05 },
            // { name: "m9", count: 1, weight: 0.01 },
        ],
        tier_lmgs: [
            { name: "bar", count: 1, weight: 5 },
            { name: "dp28", count: 1, weight: 5 },
            { name: "qbb97", count: 1, weight: 0.5 },
            { name: "m249", count: 1, weight: 0.01 },
            { name: "pkp", count: 1, weight: 0.01 },
        ],
        tier_shotguns: [
            { name: "m1100", count: 1, weight: 5 },
            { name: "m870", count: 1, weight: 5 },
            { name: "mp220", count: 1, weight: 1 },
            { name: "spas12", count: 1, weight: 1 },
            { name: "saiga", count: 1, weight: 0.1 },
            { name: "usas", count: 1, weight: 0 },
        ],
        tier_hatchet_melee: [
            { name: "fireaxe", count: 1, weight: 5 },
            { name: "katana", count: 1, weight: 1 },
            { name: "katana_rusted", count: 1, weight: 1 },
            { name: "katana_orchid", count: 1, weight: 0.1 },
            { name: "stonehammer", count: 1, weight: 0.1 },
        ],
        tier_pavilion: [
            { name: "dp28", count: 1, weight: 5 },
            { name: "bar", count: 1, weight: 5 },
            { name: "naginata", count: 1, weight: 1 },
            { name: "m9", count: 1, weight: 1 },
            { name: "pkp", count: 1, weight: 1 },
        ],
        tier_forest_helmet: [{ name: "helmet03_forest", count: 1, weight: 1 }],
        tier_imperial_outfit: [{ name: "outfitImperial", count: 1, weight: 1 }],
        tier_pineapple_outfit: [{ name: "outfitPineapple", count: 1, weight: 1 }],
        tier_tarkhany_outfit: [{ name: "outfitTarkhany", count: 1, weight: 1 }],
        tier_spetsnaz_outfit: [{ name: "outfitSpetsnaz", count: 1, weight: 1 }],
        tier_lumber_outfit: [{ name: "outfitLumber", count: 1, weight: 1 }],
        tier_verde_outfit: [{ name: "outfitVerde", count: 1, weight: 1 }],

        tier_airdrop_uncommon: [
            { name: "mk12", count: 1, weight: 0 },
            { name: "scar", count: 1, weight: 0 },
            { name: "vector", count: 1, weight: 0.75 },
            { name: "blr", count: 1, weight: 2.5 },
            { name: "mosin", count: 1, weight: 2 },
            { name: "saiga", count: 1, weight: 0 },
            { name: "deagle", count: 1, weight: 0 },
            { name: "sv98", count: 1, weight: 0.1 },
            { name: "qbb97", count: 1, weight: 1.5 },
            { name: "flare_gun", count: 1, weight: 0 },
            { name: "scout_elite", count: 1, weight: 1.5 },
        ],
        tier_airdrop_rare: [
            { name: "garand", count: 1, weight: 6 },
            { name: "mosin", count: 1, weight: 6 },
            { name: "pkp", count: 1, weight: 3 },
            { name: "m249", count: 1, weight: 0.1 },
            { name: "m4a1", count: 1, weight: 4 },
            { name: "scorpion", count: 1, weight: 5 },
            // { name: "ots38_dual", count: 1, weight: 4.5 },
        ],
        tier_airdrop_ammo: [
            { name: "45acp", count: 30, weight: 0 },
            { name: "762mm", count: 30, weight: 3 },
            { name: "556mm", count: 30, weight: 3 },
            { name: "12gauge", count: 5, weight: 3 },
        ],
        tier_airdrop_outfits: [
            { name: "", count: 1, weight: 20 },
            { name: "outfitMeteor", count: 1, weight: 0 },
            { name: "outfitHeaven", count: 1, weight: 0 },
            {
                name: "outfitGhillie",
                count: 0,
                weight: 0,
            },
        ],
        tier_airdrop_throwables: [
            { name: "frag", count: 2, weight: 1 },
            { name: "snowball", count: 2, weight: 0 },
            { name: "mirv", count: 2, weight: 0.5 },
        ],
        tier_airdrop_melee: [
            { name: "", count: 1, weight: 19 },
            { name: "katana", count: 1, weight: 7 },
            { name: "pan", count: 1, weight: 0 },
        ],
        tier_airdrop_armor: [
            { name: "helmet03", count: 1, weight: 1 },
            { name: "chest03", count: 1, weight: 1 },
            { name: "chest02", count: 1, weight: 2 },
            { name: "helmet02", count: 1, weight: 2 },
        ],
        tier_airdrop_scopes: [
            { name: "4xscope", count: 1, weight: 3 },
            // { name: "8xscope", count: 1, weight: 0 },
            // { name: "15xscope", count: 1, weight: 0 },
        ],

        tier_perks: [
            // { name: "", count: 1, weight: 20 },
            // { name: "splinter", count: 1, weight: 11.428 },
            //{ name: "scavenger", count: 1, weight: 11.428 },
            { name: "endless_ammo", count: 1, weight: 1 },
            //{ name: "takedown", count: 1, weight: 11.428 },
            { name: "field_medic", count: 1, weight: 1 },
            // { name: "bonus_assault", count: 1, weight: 11.428 },
            { name: "firepower", count: 1, weight: 1 },
            // { name: "lifesteal", count: 1, weight: 1 },
            // { name: "bulwark", count: 1, weight: 1 },
        ],
    },    
    mapGen: {
        map: {
            baseWidth: 440,
            baseHeight: 440,
            scale: { small: 1.3, large: 1.3 },
            shoreInset: 40,
            grassInset: 10,
            // rivers: {
            //     weights: [
            //         { weight: 1, widths: [15] },
            //         // { weight: 1, widths: [20, 4] },
            //         // { weight: 1, widths: [20, 8, 4] },
            //     ],
            //     smoothness: 1,
            //     spawnCabins : false,
            // },            
        },
        customSpawnRules: {
            locationSpawns: [],
        },
        densitySpawns: [
            {
                stone_01: 200,
                // crate_01: 0,
                // crate_02: 0,
                // crate_03: 0,
                // bush_01: 0,
                // cache_06: 0,
                 tree_01: 80,
                // hedgehog_01: 4 * 1.5,
                // hedgehog_02: 20 * 1.5,
                // container_01: 4 * 1.5,
                // container_02: 3 * 1.5,
                // container_03: 4 * 1.5,
                // container_04: 3 * 1.5,
                // shack_01: 3 * 1.5,
                // outhouse_01: 5 * 1.5,
                // loot_tier_1: 0,
                // loot_tier_beach: 0,
            },
        ],
        fixedSpawns: [
            {
                //barn_01: 1,
                // barn_02: 1,
                hut_01: 5,
                hut_02: 0, // spas hut
                hut_03: 1, // scout hut
                warehouse_01: 1,
                warehouse_02: 1,
                // shack_03a: 2,
                // shack_03b: 2,
                greenhouse_01: 0,
                cache_01: 0,
                cache_02: 0, // mosin tree
                cache_07: 0,
                barn_01: 2,
                // bunker_structure_01: { odds: 0.05 },
                //bunker_structure_02: 1,
                // bunker_structure_03: 1,
                // bunker_structure_04: 1,
                // bunker_structure_05: 1,
                // warehouse_complex_01: 1,
                // chest_01: 1,
                // chest_03: { odds: 0.2 },
                // mil_crate_02: { odds: 0.25 },
                // tree_02: 3,
                teahouse_complex_01su: 1,
                stone_04: 0,
                //mansion_structure_01: 1,
                // club_complex_01: 1,
            },
        ],
        randomSpawns: [
            {
                spawns: [ "police_01", 
                    "bank_01", 
                    "mansion_structure_01",
                    "club_complex_01",
                ],
                choose: 3,
            },
            {
                spawns: ["house_red_01", "house_red_02", "house_red_01", "house_red_02", ],
                choose: 3,
            },          
            // {
            //     spawns: ["police_01", "bank_01"],
            //     choose: 1,
            // },
            // {
            //     spawns: [
            //         "club_complex_01",
            //         "mansion_structure_01",
            //         // "bunker_structure_02",
            //     ],
            //     choose: 2,
            // },
            // {
            //     spawns: ["house_red_02", "house_red_01", "saloon_01"],
            //     choose: 2,
            // },
            // {
            //     spawns: ["warehouse_01", "warehouse_02", "barn_01"],
            //     choose: 2,
            // },
            // {
            //     spawns: [
            //         "silo_01",
            //         "silo_01",
            //         "silo_01",
            //     ],
            //     choose: 3,
            // },
        ],
    },
};

export const FixedLoot = util.mergeDeep({}, Main, mapDef) as MapDef;